# Generated by Django 4.1.7 on 2023-04-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ('name', 'image'), 'verbose_name_plural': 'developer'},
        ),
        migrations.RemoveField(
            model_name='developer',
            name='age',
        ),
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='address',
            field=models.TextField(max_length=250),
        ),
    ]
